site_description: Software and Data Consulting Services
site_name: Tempered Works Ltd.
site_url: https://tempered.works

site_author: brabster
copyright: Copyright &copy; 2018 - 2024 Paul Brabban

theme:
  name: material
  language: en
  favicon: favicons/favicon.ico
  logo: favicons/favicon-32x32.png
  palette:
    primary: blue grey
  features:
    - navigation.tabs
    - navigation.indexes

plugins:
  - privacy
  - glightbox
  - meta
  - search
  # - optimize needs pngquant
  - blog:
      blog_dir: .
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
        - snippets
      check_paths: true
  - def_list
  - attr_list
  - footnotes

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brabster
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/paulbrabban

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

