site_name: Tempered Works Ltd.
site_description: Software and Data Consulting Services
site_url: !ENV [SITE_URL, DEPLOY_PRIME_URL, 'http://localhost:8000']

site_author: brabster
copyright: Copyright &copy; 2018 - 2024 Paul Brabban

theme:
  name: material
  language: en
  favicon: favicon.ico
  logo: favicons/favicon-32x32.png
  palette:
    primary: blue grey
  features:
    - navigation.tabs
    - navigation.indexes
    - content.footnote.tooltips

plugins:
  - privacy
  - glightbox
  - meta
  - search
  # - optimize needs pngquant
  - blog:
      blog_dir: .
      post_url_format: "posts/{date}/{slug}"
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - optimize:
      enabled: !ENV [CI, false]
      

markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
        - snippets
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - attr_list
  - footnotes

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brabster
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/paulbrabban
    
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

