site_description: Software and Data Consulting Services
site_name: Tempered Works Ltd.
site_url: https://tempered.works

site_author: brabster

theme:
  name: material
  language: en
  favicon: assets/favicons/favicon.ico
  features:
    - navigation.tabs
    - navigation.indexes


plugins:
  - glightbox
  - meta
  - search
  # - optimize needs pngquant
  - blog:
      authors_profiles: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - def_list
  - attr_list
