site_description: Software and Data Consulting Services
site_name: Tempered Works Ltd.
site_url: https://tempered.works

site_author: brabster

theme:
  name: material
  language: en

plugins:
  - blog: {}
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      use_git: false