site_name: Tempered Works Ltd.
site_description: Software and Data Consulting Services
site_url: !ENV [SITE_URL, DEPLOY_PRIME_URL, 'http://localhost:8000']

site_author: brabster
copyright: |
  Copyright &copy; 2018 - 2024 Paul Brabban.
  Views expressed are my own and may not represent those of my employer or other associated entity.

theme:
  name: material
  language: en
  favicon: favicon.ico
  logo: favicons/favicon-32x32.webp
  palette:
    primary: blue grey
  features:
    - navigation.tabs
    - navigation.indexes
    - content.footnote.tooltips
    - content.code.copy
    - content.code.annotate

plugins:
  - privacy
  - glightbox
  - meta
  - search
  - blog:
      blog_dir: .
      post_url_format: "posts/{date}/{slug}"
      post_date_format: MMM d, yyyy
      categories_toc: true
      categories_allowed:
        - automation
        - contracts
        - insights
        - operations
        - performance
        - python
        - security
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      

markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path:
        - snippets
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brabster
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/paulbrabban
    - icon: fontawesome/solid/paper-plane
      link: mailto:paul@tempered.works

    
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

